server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harshaltrane/spring-cloud-config-store
          search-paths:
           - '*service'
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_customer?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   # properties:
   #  hibernate:
   #   dialect: org.hibernate.dialect.MySQL55Dialect
  application:
    name: customer
